// Babylon.js köprüsü: sadece kullandığımız modülleri derin import ile alırız (daha küçük paket).
// Yan etkili importlar (sahne bileşenleri, builder kayıtları) burada toplanır.
export { Engine } from '@babylonjs/core/Engines/engine.js';
export { Scene } from '@babylonjs/core/scene.js';
export { ArcRotateCamera } from '@babylonjs/core/Cameras/arcRotateCamera.js';
export { Camera } from '@babylonjs/core/Cameras/camera.js';
export { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight.js';
export { DirectionalLight } from '@babylonjs/core/Lights/directionalLight.js';
export { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator.js';
import '@babylonjs/core/Lights/Shadows/shadowGeneratorSceneComponent.js';
export { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial.js';
export { Texture } from '@babylonjs/core/Materials/Textures/texture.js';
export { DynamicTexture } from '@babylonjs/core/Materials/Textures/dynamicTexture.js';
import '@babylonjs/core/Engines/Extensions/engine.dynamicTexture.js';
export { Vector3, Vector4, Matrix, Quaternion } from '@babylonjs/core/Maths/math.vector.js';
export { Color3, Color4 } from '@babylonjs/core/Maths/math.color.js';
export { Plane } from '@babylonjs/core/Maths/math.plane.js';
export { Mesh } from '@babylonjs/core/Meshes/mesh.js';
export { TransformNode } from '@babylonjs/core/Meshes/transformNode.js';
export { VertexBuffer } from '@babylonjs/core/Buffers/buffer.js';
export { VertexData } from '@babylonjs/core/Meshes/mesh.vertexData.js';
import '@babylonjs/core/Meshes/instancedMesh.js';
import '@babylonjs/core/Meshes/thinInstanceMesh.js';
export { CreateBox } from '@babylonjs/core/Meshes/Builders/boxBuilder.js';
export { CreateCylinder } from '@babylonjs/core/Meshes/Builders/cylinderBuilder.js';
export { CreateSphere } from '@babylonjs/core/Meshes/Builders/sphereBuilder.js';
export { CreateTorus } from '@babylonjs/core/Meshes/Builders/torusBuilder.js';
export { CreatePlane } from '@babylonjs/core/Meshes/Builders/planeBuilder.js';
export { CreateGround } from '@babylonjs/core/Meshes/Builders/groundBuilder.js';
export { CreateDisc } from '@babylonjs/core/Meshes/Builders/discBuilder.js';
export { CreateLathe } from '@babylonjs/core/Meshes/Builders/latheBuilder.js';
export { CreateTube } from '@babylonjs/core/Meshes/Builders/tubeBuilder.js';
export { CreateIcoSphere } from '@babylonjs/core/Meshes/Builders/icoSphereBuilder.js';
export { CreateTorusKnot } from '@babylonjs/core/Meshes/Builders/torusKnotBuilder.js';
export { GlowLayer } from '@babylonjs/core/Layers/glowLayer.js';
import '@babylonjs/core/Layers/effectLayerSceneComponent.js';
export { Layer } from '@babylonjs/core/Layers/layer.js';
import '@babylonjs/core/Layers/layerSceneComponent.js';
export { ParticleSystem } from '@babylonjs/core/Particles/particleSystem.js';
import '@babylonjs/core/Particles/particleSystemComponent.js';
import '@babylonjs/core/Culling/ray.js';
export { FresnelParameters } from '@babylonjs/core/Materials/fresnelParameters.js';
export { ImageProcessingConfiguration } from '@babylonjs/core/Materials/imageProcessingConfiguration.js';
export { DefaultRenderingPipeline } from '@babylonjs/core/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.js';
export { SSAO2RenderingPipeline } from '@babylonjs/core/PostProcesses/RenderPipeline/Pipelines/ssao2RenderingPipeline.js';
import '@babylonjs/core/PostProcesses/RenderPipeline/postProcessRenderPipelineManagerSceneComponent.js';
import '@babylonjs/core/Rendering/geometryBufferRendererSceneComponent.js';
import '@babylonjs/core/Rendering/prePassRendererSceneComponent.js';
import '@babylonjs/core/Rendering/depthRendererSceneComponent.js';
export { ColorCurves } from '@babylonjs/core/Materials/colorCurves.js';
